name: Update Wiki Lists

permissions:
  contents: write

concurrency:
  group: "update-wiki"
  cancel-in-progress: true

on:
  workflow_dispatch:
  schedule:
    - cron: '0,30 * * * *'  # every 30 minutes

jobs:
  update-wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate Lists
        run: make update

      - name: Clone Wiki
        run: make clone-wiki

      - name: Update Wiki
        run: make update-wiki
